= simple-microservice-database

The `simple-microservice-database` project is a simple Jakarta EE application with a HTTP endpoint that is running in
https://wildfly.org[WildFly].

The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Building the application

To run the application, you use Maven:

[source,shell]
----
mvn clean package
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== PostgreSQL

[source,shell]
----
podman run --rm --name my-postgres \
    -p 5432:5432 \
    -e POSTGRES_PASSWORD=admin \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_DB=postgres \
    docker.io/library/postgres
----

== Running the application

To run the application, run the commands:

[source,shell]
----
cd target/server
./bin/standalone.sh
----

Once WildFly is running, the application can be accessed at http://localhost:8080/

== Testing the application

To run integration tests to verify the application, you use Maven:

[source,shell]
----
mvn clean package verify
----

Tests in `src/test` are run against the server in `target/server`.

== Build the Docker Image

[source,shell]
----
podman build -t my-jaxrs-app-db:latest .
----

== Run the Docker Image
[source,shell]
----
podman run --rm -p 8080:8080 -p 9990:9990 \
    -e POSTGRESQL_USER=postgres \
    -e POSTGRESQL_PASSWORD=admin \
    -e POSTGRESQL_HOST=192.168.1.43 \
    -e POSTGRESQL_PORT=5432 \
    -e POSTGRESQL_DATABASE=postgres \
    -e POSTGRESQL_JNDI=java:jboss/datasources/PostgreSQLDS \
    --name=my-jaxrs-app-db \
    my-jaxrs-app-db:latest
----

== Check the application

[source,shell]
----
curl http://127.0.0.1:8080/hello/pippo
----

== Check Liveness, Readiness and Startup Probes

[source,shell]
----
curl http://127.0.0.1:9990/health/live
----

[source,shell]
----
curl http://127.0.0.1:9990/health/ready
----

[source,shell]
----
curl http://127.0.0.1:9990/health/started
----

== Resources

* https://wildfly.org[WildFly]
* https://docs.wildfly.org[WildFly Documentation]
