
= getting-started

The `getting-started` project is a simple Jakarta EE application with a HTTP endpoint that is running in
https://wildfly.org[WildFly].

The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Building the application

To run the application, you use Maven:

[source,shell]
----
mvn clean package
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== Running the application

To run the application, run the commands:

[source,shell]
----
cd target/server
./bin/standalone.sh
----

Once WildFly is running, the application can be accessed at http://localhost:8080/

== Testing the application

To run integration tests to verify the application, you use Maven:

[source,shell]
----
mvn clean package verify
----

Tests in `src/test` are run against the server in `target/server`.

== Start PostgreSQL

[source,shell]
----
podman network create demo-network

podman run --rm --network=demo-network --name my-postgres \
    -p 5432:5432 \
    -e POSTGRES_PASSWORD=admin \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_DB=postgres \
    docker.io/library/postgres
----

== Build Docker image

[source,shell]
----
podman build -t my-jaxrs-app-db:latest .
----

== Run Docker image

[source,shell]
----
podman run --rm --network=demo-network -p 8080:8080 -p 9990:9990 \
    -e POSTGRESQL_USER=postgres \
    -e POSTGRESQL_PASSWORD=admin \
    -e POSTGRESQL_HOST=my-postgres \
    -e POSTGRESQL_PORT=5432 \
    -e POSTGRESQL_DATABASE=postgres \
    -e POSTGRESQL_JNDI=java:jboss/datasources/PostgreSQLDS \
    --name=my-jaxrs-app-db \
    my-jaxrs-app-db:latest
----

== Deploy to Kubernetes

[source,shell]
----
kubectl apply -f postgres-configmap.yaml
kubectl apply -f postgres-deployment.yaml
kubectl apply -f postgres-service.yaml
kubectl apply -f deployment-my-jaxrs-app-db.yaml
kubectl expose deployment.apps/my-jaxrs-app-db-deployment --type=NodePort --port=8080
----

== Resources

* https://wildfly.org[WildFly]
* https://docs.wildfly.org[WildFly Documentation]
