= simple-microservice-infinispan

The `simple-microservice-infinispan` project is a simple Jakarta EE application with a HTTP endpoint that is running in
https://wildfly.org[WildFly].

The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Building the application

To run the application, you use Maven:

[source,shell]
----
mvn clean package
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== Running the application

To run the application, run the commands:

[source,shell]
----
cd target/server
./bin/standalone.sh
----

Once WildFly is running, the application can be accessed at http://localhost:8080/

== Testing the application

To run integration tests to verify the application, you use Maven:

[source,shell]
----
mvn clean package verify
----

Tests in `src/test` are run against the server in `target/server`.

== Build the Docker Image

[source,shell]
----
podman build -t my-jaxrs-app:latest .
----

== Run the Docker Image
[source,shell]
----
podman run --rm -p 8080:8080 -p 9990:9990 \
    --name=my-jaxrs-app \
    my-jaxrs-app
----

== Check the application

[source,shell]
----
curl http://127.0.0.1:8080/hello/pippo
----

== Check Liveness, Readiness and Startup Probes

[source,shell]
----
curl http://127.0.0.1:9990/health/live
----

[source,shell]
----
curl http://127.0.0.1:9990/health/ready
----

[source,shell]
----
curl http://127.0.0.1:9990/health/started
----

== Infinispan

=== Start Infinispan

[source,shell]
----
podman pull quay.io/infinispan/server:latest

# -p 11222:11222
podman run --rm --net=host -e USER="admin" -e PASS="123pippobaudo" quay.io/infinispan/server:latest
----

=== Connect to Infinispan

[source,shell]
----
podman run --rm --net=host -it quay.io/infinispan/cli:latest
  connect http://admin:123pippobaudo@0.0.0.0:11222
  ls caches
podman run --rm --net=host -it quay.io/infinispan/cli:latest
  connect http://0.0.0.0:11222 -u admin -p 123pippobaudo
  ls caches
----

== Resources

* https://wildfly.org[WildFly]
* https://docs.wildfly.org[WildFly Documentation]
