
= simple-microservice-jms

The `simple-microservice-jms` project is a simple Jakarta EE application with a HTTP endpoint that is running in
https://wildfly.org[WildFly].

The `simple-microservice-jms` project sends messages to an Artemis JMS Broker and then consumes those messages using
a Message Driven Bean.

== Building the application

To build the application, you use Maven:

[source,shell]
----
mvn clean package
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== Start Artemis

[source,shell]
----
podman network create demo-network

podman run --rm --name my-artemis \
    --network=demo-network \
    -p 8161:8161 \
    -p 61616:61616\
    -e AMQ_USER=admin \
    -e AMQ_PASSWORD=admin \
    -e AMQ_DATA_DIR=//home/jboss/data \
    quay.io/artemiscloud/activemq-artemis-broker-kubernetes:latest
----

== Build Docker image

[source,shell]
----
podman build -t my-jms-app:latest .
----

== Run Docker image

[source,shell]
----
podman run --rm --network=demo-network -p 8080:8080 -p 9990:9990 \
    --name=my-jms-app \
    -e JBOSS_MESSAGING_CONNECTOR_HOST=my-artemis \
    my-jms-app:latest
----

== Deploy to Kubernetes

[source,shell]
----
podman tag my-jaxrs-app quay.io/tborgato/my-jms-app
podman push quay.io/tborgato/my-jms-app
----

NOTE: in the above commands, replace `tborgato` with your personal account

[source,shell]
----
kubectl apply -f kubernetes/artemis-deployment.yaml
kubectl apply -f kubernetes/artemis-service.yaml
kubectl apply -f kubernetes/deployment-my-jms-app.yaml
kubectl expose deployment.apps/my-jms-app-deployment --type=NodePort --port=8080
----

NOTE: in the above files, replace `tborgato` with your personal account

== Resources

* https://wildfly.org[WildFly]
* https://docs.wildfly.org[WildFly Documentation]
