
= getting-started

The `getting-started` project is a simple Jakarta EE application with a HTTP endpoint that is running in
https://wildfly.org[WildFly].

The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Building the application

To run the application, you use Maven:

[source,shell]
----
mvn clean package
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== Running the application

To run the application, run the commands:

[source,shell]
----
cd target/server
./bin/standalone.sh
----

Once WildFly is running, the application can be accessed at http://localhost:8080/

== Testing the application

To run integration tests to verify the application, you use Maven:

[source,shell]
----
mvn clean package verify
----

Tests in `src/test` are run against the server in `target/server`.

== Start Artemis

[source,shell]
----
podman network create demo-network

podman run --rm --name my-artemis \
    --network=demo-network \
    -p 8161:8161 \
    -p 61616:61616\
    -e AMQ_USER=admin \
    -e AMQ_PASSWORD=admin \
    -e AMQ_DATA_DIR=//home/jboss/data \
    quay.io/artemiscloud/activemq-artemis-broker-kubernetes:latest
----

== Build Docker image

[source,shell]
----
podman build -t my-jms-app:latest .
----

== Run Docker image

[source,shell]
----
podman run --rm --network=demo-network -p 8080:8080 -p 9990:9990 \
    --name=my-jms-app \
    -e JBOSS_MESSAGING_CONNECTOR_HOST=my-artemis \
    my-jms-app:latest
----

== Deploy to Kubernetes

[source,shell]
----
kubectl apply -f artemis-deployment.yaml
kubectl apply -f artemis-service.yaml
kubectl apply -f deployment-my-jms-app.yaml
kubectl expose deployment.apps/my-jms-app-deployment --type=NodePort --port=8080
----

== Resources

* https://wildfly.org[WildFly]
* https://docs.wildfly.org[WildFly Documentation]
