= simple-microservice-jms

The `simple-microservice-jms` project is a simple Jakarta EE application with a HTTP endpoint that is running in
https://wildfly.org[WildFly].

The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Building the application

To run the application, you use Maven:

[source,shell]
----
mvn clean package
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== Running the application

To run the application, run the commands:

[source,shell]
----
cd target/server
./bin/standalone.sh
----

Once WildFly is running, the application can be accessed at http://localhost:8080/

== Testing the application

To run integration tests to verify the application, you use Maven:

[source,shell]
----
mvn clean package verify
----

Tests in `src/test` are run against the server in `target/server`.

== Build the Docker Image

[source,shell]
----
podman build -t my-jaxrs-app:latest .
----

== Run the Docker Image
[source,shell]
----
podman run --rm -p 8080:8080 -p 9990:9990 \
    --name=my-jaxrs-app \
    my-jaxrs-app
----

== Check the application

[source,shell]
----
curl http://127.0.0.1:8080/hello/pippo
----

== Check Liveness, Readiness and Startup Probes

[source,shell]
----
curl http://127.0.0.1:9990/health/live
----

[source,shell]
----
curl http://127.0.0.1:9990/health/ready
----

[source,shell]
----
curl http://127.0.0.1:9990/health/started
----

== ActiveMQ Artemis

- link:https://docs.wildfly.org/wildfly-proposals/messaging/WFLY-10518_artemis_no_local_broker.html[Connections to remote Artemis broker must not require local Artemis instance]
- link:https://github.com/jms-ra/generic-jms-ra?tab=readme-ov-file#example-ejb3-mdb[Example EJB3 MDB]
- link:https://activemq.apache.org/components/artemis/documentation/latest/docker.html[ActiveMQ Artemis - Docker]

=== Start ActiveMQ Artemis

[source,bash,subs="normal"]
----
$ podman run --rm --name activemq-artemis -e ARTEMIS_USER=artemis -e ARTEMIS_PASSWORD=123PIPPOBAUDO -p 61616:61616 -p 8161:8161  apache/activemq-artemis:latest-alpine
----

== Test WF + ActiveMQ Artemis

Hit the following URL and you will see a message sent to "ActiveMQ Artemis" that is immediately consumed by the MDB:

[source,shell]
----
curl http://localhost:8080/hello/message/send?content=SOME-MESSAGE
----


== Resources

* https://wildfly.org[WildFly]
* https://docs.wildfly.org[WildFly Documentation]
